# Generated by Django 4.2.7 on 2026-05-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dedicated_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dedicated_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
