# Generated by Django 4.2.7 on 2026-05-31 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_dedicated_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('discount_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('send_email_notification', models.BooleanField(default=False, help_text='Check this to broadcast this offer to all registered users via email.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='api.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
